### ISSUE TITLE
Plowshare

### ISSUE THREAD

**Issue by steom** [alllexx88/Optware-ng#13]
>Your shell is too old. Bash 4.1+ is required.
>Your version is 3.2.54(1)-release

Entware bash version is 4.3.42-1

**Comment by alllexx88** [comment]
I've upgraded bash to 4.3.42 some while ago: a21e88ceb0f9dd5082873abd14ffcd36c53ec77d, but I can't update the feeds atm, since I'm in the process of rebuilding everything from scratch
