### ISSUE TITLE
compiling 

### ISSUE THREAD

**Issue by steom** [alllexx88/Optware-ng#14]
hi allexx88
how to compile the .ipk packages with the router
from the github repository without wait that the feeds is updated?
what is the right command line?
best regards

**Comment by alllexx88** [comment]
@steom please tell me which feed you use, and I can upload the .ipk for you. No way to compile it on the router: Optware-ng uses cross-compilation, no native compiling.

**Comment by steom** [comment]
ARMv7 EABI softfloat

**Comment by alllexx88** [comment]
@steom http://optware-ng.zyxmon.org/test/buildroot-armeabi-ng/bash_4.3.42-1_arm.ipk

**Comment by steom** [comment]
Works fine! Thanks!

**Comment by steom** [comment]
@alllexx88 can you try plowshare? Plowmod --install
Plowmod --status
Plowmod --update
There are errors with busybox and git?

**Comment by alllexx88** [comment]
@steom don't know about busybox (got no errors), but git error is fixed by installing git:

```
ipkg update
ipkg install git
```

**Comment by steom** [comment]
plowmod --update
/opt/bin/plowmod: line 335: /dev/fd/62: No such file or directory
find: unrecognized: -mindepth
BusyBox v1.20.2 (2015-11-02 20:32:51 MSK) multi-call binary.

Usage: find [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

        -follow         Follow symlinks

Actions:
        ! ACT           Invert ACT's success/failure
        ACT1 [-a] ACT2  If ACT1 fails, stop, else do ACT2
        ACT1 -o ACT2    If ACT1 succeeds, stop, else do ACT2
                        Note: -a has higher priority than -o
        -name PATTERN   Match file name (w/o directory name) to PATTERN
        -iname PATTERN  Case insensitive -name
        -mtime DAYS     mtime is greater than (+N), less than (-N),
                        or exactly N days in the past
If none of the following actions is specified, -print is assumed
        -print          Print file name
        -print0         Print file name, NUL terminated
        -exec CMD ARG ; Run CMD with all instances of {} replaced by
                        file name. Fails if CMD exits with nonzero

find: unrecognized: -mindepth
BusyBox v1.20.2 (2015-11-02 20:32:51 MSK) multi-call binary.

Usage: find [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

        -follow         Follow symlinks

Actions:
        ! ACT           Invert ACT's success/failure
        ACT1 [-a] ACT2  If ACT1 fails, stop, else do ACT2
        ACT1 -o ACT2    If ACT1 succeeds, stop, else do ACT2
                        Note: -a has higher priority than -o
        -name PATTERN   Match file name (w/o directory name) to PATTERN
        -iname PATTERN  Case insensitive -name
        -mtime DAYS     mtime is greater than (+N), less than (-N),
                        or exactly N days in the past
If none of the following actions is specified, -print is assumed
        -print          Print file name
        -print0         Print file name, NUL terminated
        -exec CMD ARG ; Run CMD with all instances of {} replaced by
                        file name. Fails if CMD exits with nonzero

**Comment by steom** [comment]
plowmod --install
plowmod: adding legacy (default) repository: https://github.com/mcrapet/plowshare-modules-legacy.git
- installing new directory: /root/.config/plowshare/modules.d/legacy.git
ERROR: directory exists but it does not appear to be a git repository, abort

**Comment by steom** [comment]
plowmod --status
/opt/bin/plowmod: line 147: /dev/fd/62: No such file or directory
find: unrecognized: -mindepth
BusyBox v1.20.2 (2015-11-02 20:32:51 MSK) multi-call binary.

Usage: find [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

        -follow         Follow symlinks

Actions:
        ! ACT           Invert ACT's success/failure
        ACT1 [-a] ACT2  If ACT1 fails, stop, else do ACT2
        ACT1 -o ACT2    If ACT1 succeeds, stop, else do ACT2
                        Note: -a has higher priority than -o
        -name PATTERN   Match file name (w/o directory name) to PATTERN
        -iname PATTERN  Case insensitive -name
        -mtime DAYS     mtime is greater than (+N), less than (-N),
                        or exactly N days in the past
If none of the following actions is specified, -print is assumed
        -print          Print file name
        -print0         Print file name, NUL terminated
        -exec CMD ARG ; Run CMD with all instances of {} replaced by
                        file name. Fails if CMD exits with nonzerofind: unrecognized: -mindepth


BusyBox v1.20.2 (2015-11-02 20:32:51 MSK) multi-call binary.

Usage: find [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

        -follow         Follow symlinks

Actions:
        ! ACT           Invert ACT's success/failure
        ACT1 [-a] ACT2  If ACT1 fails, stop, else do ACT2
        ACT1 -o ACT2    If ACT1 succeeds, stop, else do ACT2
                        Note: -a has higher priority than -o
        -name PATTERN   Match file name (w/o directory name) to PATTERN
        -iname PATTERN  Case insensitive -name
        -mtime DAYS     mtime is greater than (+N), less than (-N),
                        or exactly N days in the past
If none of the following actions is specified, -print is assumed
        -print          Print file name
        -print0         Print file name, NUL terminated
        -exec CMD ARG ; Run CMD with all instances of {} replaced by
                        file name. Fails if CMD exits with nonzero

-------------------------------------------------------------------------------
Your plowshare installation has currently no module.
(/root/.config/plowshare/modules.d/ is empty)

In order to use plowdown you must install some modules. Here is a quick start:
$ plowmod --install
-------------------------------------------------------------------------------

**Comment by alllexx88** [comment]
@steom this goes beyond original issue, you should've created a new one.

    /opt/bin/plowmod: line 147: /dev/fd/62: No such file or directory

Execute this command:
```
ln -s /proc/self/fd /dev/fd
```
it should probably be added to some init script.

    find: unrecognized: -mindepth
    BusyBox v1.20.2 (2015-11-02 20:32:51 MSK) multi-call binary.

Your firmware's busybox doesn't support '-mindepth' `find` switch.

    installing new directory: /root/.config/plowshare/modules.d/legacy.git ERROR: directory exists but it does not appear to be a git repository, abort

`plowmod` uses '-C' `git` switch, which isn't supported by current Optware-ng `git` (1.8.4.2).

I've fixed last two issues and also updated the feeds:

```
ipkg update
ipkg upgrade
# optional:
ipkg remove util-linux-ng
# (plowshare now uses util-linux package, which is never than util-linux-ng.
# I plan to remove util-linux-ng in the future)
```

Now `plowmod` should work fine. Just remember to always add `--modules-directory=/opt/share/plowshare/modules` switch, otherwise `plowmod` installs to '/root/.config/plowshare/modules.d/', which doesn't survive a reboot on a router.

**Comment by alllexx88** [comment]
@steom Never mind the `--modules-directory=/opt/share/plowshare/modules` part. After 9fa87f3daa69e7c6d47edf4b70d1be4d1d5633cf commit plowshare configs are stored in `/opt/etc/plowshare` if running as root, and modules --- in `/opt/etc/plowshare/modules.d`

**Comment by steom** [comment]
ipkg install busybox
Package busybox (1.23.0-1) installed in /opt/ is up to date.
Nothing to be done
Successfully terminated.

plowdown
find: unrecognized: -mindepth
BusyBox v1.20.2 (2015-11-02 20:32:51 MSK) multi-call binary.

**Comment by alllexx88** [comment]
@steom should be fixed now:
a94c25c2271ee5c14d12c19821e507b937a8c244 upgrades `git` to the currently latest 2.6.3
2bcfb79a82c017b31ec515590ef09156bafc0026 should finally patch `plowshare` to use Optware-ng findutils `find`

**Comment by steom** [comment]
now it seems to work I can confirm
well done!
