### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by steom** [alllexx88/Optware-ng#16]
What type of packages is doable to port/add to optware-ng armv7 router repository?
Most/all the .deb packages for example?
Someday it will be possible to see added packages like openjava headless, bubbleupnp, serviio without the need of running a chrooted debian?

**Comment by alllexx88** [comment]
Unlike Debian, Optware-ng uses cross-compilation, and some packages are hard/next-to-impossible to cross-compile. Also, some have numerous GUI dependencies, which require a lot of work to satisfy. Create issues for packages you'd like to see in Optware-ng, and I'll look into adding them when I can.

**Comment by steom** [comment]
right, many thanks
