### ISSUE TITLE
Plex

### ISSUE THREAD

**Issue by steom** [alllexx88/Optware-ng#17]
is possible to make a optware-ng package?
plex for armv7 had audio transcode capability.
https://goo.gl/7HicZf

there is already armv7 packages for:
Synology
https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/PlexMediaServer-0.9.12.19.1537-f38ac80-arm7.spk

Drobo 5N
https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/plex.tgz

Seagate NAS
https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/com.plex.plexmediaserver-0.9.12.19.1537-f38ac80-armv7.rbw

Western Digital MyCloud
https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/WDMyCloudMirror_plexmediaserver_091219.1537-f38ac80.bin
https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/WDMyCloudEX2_plexmediaserver_091219.1537-f38ac80.bin
https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/WDMyCloudEX2100_plexmediaserver_091219.1537-f38ac80.bin
https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/WDMyCloudEX4100_plexmediaserver_091219.1537-f38ac80.bin

**Comment by alllexx88** [comment]
Plex Media Server is closed-source (see [here](https://en.wikipedia.org/wiki/Plex_(software))), and therefore cannot be added to Optware-ng

**Comment by elRadix** [comment]
@steom @alllexx88 do you know how this can be installed? I'd like to run this on the Netgear R7000 or through debian-chroot? Is there a wiki I can follow somewhere ?

**Comment by TeHashX** [comment]
Try this :)
https://www.hqt.ro/plex-media-server-through-debian-arm/
