### ISSUE TITLE
megatools

### ISSUE THREAD

**Issue by steom** [alllexx88/Optware-ng#19]
package request
megatools - command line client application for Mega
https://github.com/megous/megatools

**Comment by alllexx88** [comment]
Added: https://github.com/alllexx88/Optware-ng/commit/76c96918644f4b765cfc221dfb493c2a1044aeb1

**Comment by steom** [comment]
ERROR: Can't login to mega.co.nz: API call 'us' failed: HTTP POST failed: TLS ba
ckend not found, please install glib-networking.

**Comment by alllexx88** [comment]
Need to add `glib-networking` package, which is currently missing. Will look into it.

**Comment by alllexx88** [comment]
I've added `glib-networking`, please test `megatools` again:

```
ipkg update
ipkg upgrade
```

**Comment by steom** [comment]
Good, signing in...

Now works
Thanks!!

**Comment by alllexx88** [comment]
Great, closing issue...
