### ISSUE TITLE
Mipsel py27-cryptography md5sum mismatch

### ISSUE THREAD

**Issue by cricket007** [alllexx88/Optware-ng#2]
I'm trying to download deluge (or deluge-develop) on an ASUS AC66U, and it seems to error out at the step of installing py27-cryptography with an md5sum mismatch.  
Here's the steps I've done. 
```bash
rm -rf /opt/*
wget -O - http://optware-ng.zyxmon.org/buildroot-mipsel/buildroot-mipsel-bootstrap.sh | sh
ipkg update
ipkg install py27-cryptography
  Installing py27-cryptography (0.9.3-1) to /opt/...
  Downloading http://optware-ng.zyxmon.org/buildroot-mipsel/py27-cryptography_0.9.3-1_mipsel.ipk
  Nothing to be done
  Successfully terminated.
  Collected errors:
  Package py27-cryptography md5sum mismatch. Either the ipkg or the package index are corrupt. Try 'ipkg update'.
```

So I run ```ipkg update```, but that doesn't really help because I just ran that less than a minute before.

**Comment by alllexx88** [comment]
Hi, I'm currently away from home on vacation, so can't repeat or fix this.
Could you for now try '-force-checksum' ipkg switch?

ipkg -force-checksum install py27-cryptography
13 серп. 2015 00:29 "Jordan Moore" <notifications@github.com> пише:

**Comment by cricket007** [comment]
Ah, sorry for interrupting your vacation! 

I run that, then it says it can't find the package at all... Pretty sure I spelled it correctly because if I remove the ```-force-checksum``` flag I get the same error as before
```bash
ipkg -force-checksum install py27-cryptography
    Nothing to be done
    An error ocurred, return value: 4.
    Collected errors:
    Cannot find package py27-cryptography.
    Check the spelling or perhaps run 'ipkg update'
```

**Comment by alllexx88** [comment]
It's OK, don't worry:-)
I must have forgotten to upload the latest ipk of the package (0.9.3-1).
Please browse http://optware-ng.zyxmon.org/buildroot-mipsel for previous
version of the package, download and install with

ipkg install py27-cryptography*.ipk

From the location that contains downloaded package.

I'll fix this the proper way as soon as I get home (after August 22nd)
13 серп. 2015 21:41 "Jordan Moore" <notifications@github.com> пише:

**Comment by alllexx88** [comment]
Fixed
