### ISSUE TITLE
DNScrypt and HW-Clock - Package Request

### ISSUE THREAD

**Issue by mattanguige** [alllexx88/Optware-ng#20]
Hi,

Any chance you could add dnscrypt and hw-clock as per this.. https://github.com/RMerl/asuswrt-merlin/wiki/Secure-DNS-queries-using-DNSCrypt

Many thanks

**Comment by alllexx88** [comment]
These should be relatively simple to add. They look to cross-compile well, and there's only one missing dependency for this: libsodium
Will look into this

**Comment by alllexx88** [comment]
`dnscrypt-proxy` and `fake-hwclock` packages added. Please test

**Comment by alllexx88** [comment]
@mattanguige got no response, so closing for now. Re-open if needed.
