### ISSUE TITLE
svn

### ISSUE THREAD

**Issue by pwallner** [alllexx88/Optware-ng#21]
would it be possible to update package "svn" to support http download? 

E.g. if I try to download with "svn checkout http://...." I receive this error:
svn: E170000: Unrecognized URL scheme for 'http://.....'

It seems that we have a compiled Subversion without serf library used for HTTP/HTTPS protocol: http://serf.apache.org/

If you run svn --version the output should include something like this:
* ra_neon : Module for accessing a repository via WebDAV protocol using Neon.
  - handles 'http' scheme
  - handles 'https' scheme
or

* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - handles 'http' scheme
  - handles 'https' scheme

thank you,
Patrick

**Comment by alllexx88** [comment]
It seems that we have a compiled Subversion without serf library used for HTTP/HTTPS protocol: http://serf.apache.org/

You're absolutely right, thanks for noticing this. Will look into it soon.

**Comment by pwallner** [comment]
Thank you! 

I have compiled oscam if you are interested? Or can I upload a package to the repository?

Best regards 
Patrick

**Comment by alllexx88** [comment]
Looks like cross-compiling oscam is pretty straightforward. I will add it sometime soon.

**Comment by alllexx88** [comment]
Earlier, Optware used Neon for HTTP/HTTPS schema, but Subversion 1.8.x has ra_neon support removed. Fixed this by adding `libserf`:

```
[root@unknown root]$ svn --version
svn, version 1.8.14 (r1692801)
   compiled Nov 21 2015, 13:50:25 on arm-unknown-linux-gnu

Copyright (C) 2015 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.8
  - handles 'http' scheme
  - handles 'https' scheme
```

Thanks for the report, @pwallner
