### ISSUE TITLE
Add new package: oscam

### ISSUE THREAD

**Issue by alllexx88** [alllexx88/Optware-ng#23]
Add new package oscam:
http://www.streamboard.tv/oscam/wiki/crosscompiling

So that I don't forget about it

**Comment by pwallner** [comment]
In the meantime you can use my ipk (remove .txt Extension and unzip the file)
[oscam_1.20-xxxxx_arm.zip.txt](https://github.com/alllexx88/Optware-ng/files/36470/oscam_1.20-xxxxx_arm.zip.txt)

**Comment by alllexx88** [comment]
Package `oscam` added and uploaded. Please test and report back

**Comment by pwallner** [comment]
It's 1.10 and old, can you make actual version 1.20 r11159?

Thank you
Patrick

**Comment by alllexx88** [comment]
It's not old: revision 11158 (was the latest then). I just called 1.10:
didn't check svn tags, and thought 1.10 was the latest release version
17 лист. 2015 21:37 "MC Pat" <notifications@github.com> пише:

**Comment by pwallner** [comment]
Tested and running!

Few comments:
version is 1.20 (not 1.10)

Include this files in the ipk

### data:
#### /opt/etc/init.d/S30oscam
```
#!/bin/sh

start() {
    echo -n "Starting oscam: "
    if [ -n "`pidof oscam`" ]; then
	echo "Already running"
	return
    fi
    /opt/bin/oscam -b -c /opt/etc/oscam
    echo "Done!"
    return
}
stop() {
    if [ -n "`pidof oscam`" ]; then
        echo -n "Shutting down oscam: "
        /bin/kill `cat /tmp/.oscam/oscam.pid` 2>/dev/null
        sleep 3
        if [ -n "`pidof oscam`" ]; then
            echo "Failed to stop oscam"
            return
        fi
        echo "Done!"
        return
    else
        echo "Oscam not running"
        return
    fi
}

restart() {
    stop
    start
}
status() {
    if [ -n "`pidof oscam`" ]; then
	echo "Oscam is running"
	return
    fi
    echo "Oscam not running"
    return
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  status)
	status
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac
exit $?
```

### control:
#### conffiles
```
/opt/etc/init.d/S30oscam
```
#### postinst
```
#!/bin/sh
echo "Starting oscam..."
/opt/etc/init.d/S30oscam start
exit 0
```
#### preinst
```
#!/bin/sh
echo "Checking for an running version of oscam..."
if [ -n "`pidof oscam`" ]; then
    /bin/kill `cat /tmp/.oscam/oscam.pid` 2>/dev/null
    sleep 3
    if [ -n "`pidof oscam`" ]; then
        echo "Failed to stop oscam"
    fi
    echo "oscam stopped"
    echo "Proceeding to installation..."
else
    echo "oscam was not running"
    echo "Proceeding to installation..."
fi
exit 0
```
#### prerm
```
#!/bin/sh
echo "Checking for an running version of oscam..."
if [ -n "`pidof oscam`" ]; then
	/bin/kill `cat /tmp/.oscam/oscam.pid` 2>/dev/null
    	sleep 3
    	if [ -n "`pidof oscam`" ]; then
        	echo "Failed to stop oscam"
    	fi
	echo "oscam was running and stopped"
	echo "Proceeding to uninstallation..."
else
	echo "oscam was not running"
	echo "Proceeding to uninstallation..."
fi
exit 0
```

Thank you for supporting oscam. Works great!

Patrick

**Comment by alllexx88** [comment]
You're welcome, Partick.

I've added rc and postinst/prerm scripts. I chose to use `killall` instead of `kill`, since I doubt we'll need to run some other binary named `oscam`, so using `killall` is more glitch-proof.

**Comment by alllexx88** [comment]
Closing for now. Re-open if needed, e.g., in case of issues with rc script
