### ISSUE TITLE
midnight commander - unable to copy with F5 after glib update

### ISSUE THREAD

**Issue by tomasiek** [alllexx88/Optware-ng#26]
When trying to copy a file using F5 mc closes with the text "aborted"
The problem appeared some 2-3 days ago, after last update of glib package (from version 2.43.92-1 to version  2.47.1-1). When I downgrade glib to 2.47.1-1 everything is ok.

**Comment by alllexx88** [comment]
I tried using F5 with `mc` with i686, mipsel-ng and armeabi-ng feeds, and the issue you reported indeed happened, but only with mipsel-ng feed. I think, `mc` simply has to be re-compiled with current glib. I'll look into it, thanks

**Comment by alllexx88** [comment]
Fixed after upgrading `glib` to the latest. My guess is that `glib` had to be recompiled after uclibc-ng upgrade. Anyway, it works on my mipsel router now. Please test and confirm.

**Comment by tomasiek** [comment]
Everything works. Thanks.
