### ISSUE TITLE
Arm wget link wrong

### ISSUE THREAD

**Issue by TeHashX** [alllexx88/Optware-ng#3]
Hi,
wget -O - http://optware-ng.zyxmon.org/buildroot-i686/buildroot-armeabi-bootstrap.sh | sh
should be
wget -O -http://optware-ng.zyxmon.org/buildroot-armeabi/buildroot-armeabi-bootstrap.sh

![screenshot-2015-08-16-20 57](https://cloud.githubusercontent.com/assets/1405188/9294556/9d46ea3e-4459-11e5-9c3c-76a9a5498397.png)

**Comment by alllexx88** [comment]
Hi,
Thanks for the notice. This has already been reported, but I can't fix it
until I get home after August 22nd. Right now I only have my phone with me
which is not very fit for this kind of task. Searching Play Store shows
there're some apps that should work with GitHub, but there's insufficient
memory on my device to clone Optware-ng :-)
16 серп. 2015 19:59 "TeHashX" <notifications@github.com> пише:

**Comment by cricket007** [comment]
Welcome, but I accidentally added an additional ```/```
