### ISSUE TITLE
PHP-MYSQLI Package Request

### ISSUE THREAD

**Issue by TeHashX** [alllexx88/Optware-ng#32]
Trying to setup OsTicket and one of requirements are php-msqli, without this installer cannot continue.
Another package is already available and installed but installer cannot see it - "php-imap"
The last one is "APC extension" but is not important at all.

![osticket](https://cloud.githubusercontent.com/assets/1405188/11797319/dc5278d6-a2ca-11e5-9a3f-2c458494cca0.png)

**Comment by alllexx88** [comment]
php mysqli extension is provided by `php-mysql` package. `php-imap` package also depends on `libpam`. I'll add the dependency, thanks for the report.

**Comment by alllexx88** [comment]
As for apc extension, it isn't available for anything newer than php 5.4 (and even for 5.4 it's in beta state).

**Comment by alllexx88** [comment]
I believe `php-imap` is fixed now.

**Comment by TeHashX** [comment]
All fine now :+1:  thanks

![osticket2](https://cloud.githubusercontent.com/assets/1405188/11857422/c9abb304-a460-11e5-9a76-521f138dbadc.png)
