### ISSUE TITLE
wget error: unable to bootstrap. 

### ISSUE THREAD

**Issue by cswl** [alllexx88/Optware-ng#33]
Downloading http://optware-ng.zyxmon.org/buildroot-armeabihf/Packages.gz
An error ocurred, return value: 1.
Collected errors:
ipkg_download: ERROR: Command failed with return value 127: `wget --passive-ftp    -q -P /opt/ipkg-mWGlKd http://optware-ng.zyxmon.org/buildroot-armeabihf/Packages.gz'
Nothing to be done
An error ocurred, return value: 4.
Collected errors:
Cannot find package glibc-locale.
Check the spelling or perhaps run 'ipkg update

maybe due to busybox not support --passive-ftp option

**Comment by alllexx88** [comment]
What hardware are you using? Currently, ipkg is patched to not use `--passive-ftp` option, but only for uclibc targets. Maybe I should apply this patch for glibc targets too. That being said, are you sure you're bootstrapping the right feed? What hardware do you have, does it have an FPU?

**Comment by alllexx88** [comment]
does it have an FPU?

Ah, sorry, that was a silly question. If ipkg-static binary from buildroot-armeabihf executed, it means your hw does have an FPU. I've fixed this and will upload the binaries a bit later.
