### ISSUE TITLE
Request for some php modules for OwnCloud

### ISSUE THREAD

**Issue by TeHashX** [alllexx88/Optware-ng#34]
Trying to install OwnCloud On mipsel router rt-ac66u through optware-ng, but after I install some of available packages, when I access owncloud default webpage I get "500 - Internal Server Error" and in lighttpd error.log
````
2015-12-22 23:34:52: (mod_fastcgi.c.2543) unexpected end-of-file (perhaps the fastcgi process died): pid: 1065 socket: unix:/tmp/php-fcgi.sock-0 
2015-12-22 23:34:52: (mod_fastcgi.c.3329) response not received, request sent: 1504 on socket: unix:/tmp/php-fcgi.sock-0 for /owncloud/index.php?, closing connection
````
I remember to get same errors when installed through entware-ng https://www.hqt.ro/owncloud-through-lighttpd-entware-ng/ but after loaded all modules, all fine

This modules are required:
````
php5-mod-ctype php5-mod-curl php5-mod-dom php5-mod-fileinfo php5-mod-gd \
php5-mod-hash php5-mod-json php5-mod-mysql php5-mod-pdo \
php5-mod-pdo-sqlite php5-mod-session php5-mod-simplexml \
php5-mod-sqlite3 php5-mod-xml php5-mod-xmlwriter php5-mod-zip
````
And only some are available on optware-ng

**Comment by alllexx88** [comment]
They're all there already, actually, just most of them not shipped as separate packages, but provided by `php` package.

**Comment by alllexx88** [comment]
I was able to get owncloud to work. It looks that `pdo_sqlite` extension is broken. After I commented out line
```
extension=pdo_sqlite.so
```
in `/opt/etc/php.ini` and restarted `lighttpd`, I was able to setup owncloud 8.2.2 using mysql.

I don't have a fix for `pdo_sqlite`, but at least OC is working

**Comment by TeHashX** [comment]
Thanks for the "fix", working great
