### ISSUE TITLE
Nginx update

### ISSUE THREAD

**Issue by TeHashX** [alllexx88/Optware-ng#37]
Hi, can you update nginx web server to v1.9.9 please?
Trying to install owncloud through lighttpd but performance is really bad and current nginx v1.0.14 is kind of old.
Thanks

**Comment by alllexx88** [comment]
Updated to 1.9.9. Haven't tested it, please test if possible

**Comment by TeHashX** [comment]
I can't find v1.9.9

**Comment by TeHashX** [comment]
Ok, installed nginx v1.9.9 mipsel but can't start it, I don'd get any output in log or with nginx -v

**Comment by alllexx88** [comment]
@TeHashX sorry, I'm away from PC, will look into it ASAP (in 10 days approx)

**Comment by alllexx88** [comment]
Should be fixed now.

**Comment by TeHashX** [comment]
Thanks, working fine with php too, the only way to start php-fcgi -b 127.0.0.1:9000 is to create an init.d script, do you know another way?
