### ISSUE TITLE
transmissiondcfp 2.77 14636

### ISSUE THREAD

**Issue by cfpp2p** [alllexx88/Optware-ng#42]
New version of transmissiondcfp  2.77 14636 for  transmissiondcfp.mk

TRANSMISSIONDCFP_VERSION=2.77+14636
TRANSMISSIONDCFP_ALT_VERSION=2.77plus14636
TRANSMISSIONDCFP_ALT2_VERSION=2.77plus14636

     sha512      
transmissiondcfp-2.77+14636.tar.bz2
transmissiondcfp-2.77plus14636.tar.bz2
 
2A3137354E04BB34F0E7A6D44B2F2685AF33E3EB8E6714B928612CF9719A9A299F6D1C1065AB752359B19B5EF17C86102712ADCB8F7A36F3DAC2951C8D3AA5B1

**Comment by cfpp2p** [comment]
Sorry...  please revision 14664
https://github.com/alllexx88/Optware-ng/pull/43  -->  https://github.com/cfpp2p/Optware-ng/commit/8f08ea4af0eada41903ae17554c414af47ac3054

**Comment by alllexx88** [comment]
Merged, thanks
