### ISSUE TITLE
is possible add shellinabox in optware-ng repo ?

### ISSUE THREAD

**Issue by armando-basile** [alllexx88/Optware-ng#9]
Hi alllexx88,
i would like to build (and packaging) and use https://github.com/shellinabox/shellinabox that is an ssh ajax client. Could you help me ?

**Comment by alllexx88** [comment]
@armando-basile I've [added](https://github.com/alllexx88/Optware-ng/commit/8914b26c5dda475bc3aecb949ecb6f456fab917c) this package, but I'm now in the process of fixing broken sourcecode links, so the binaries will arrive later. You can compile it yourself (compile new `libpam` dependency too), or just wait a little

**Comment by alllexx88** [comment]
@armando-basile I took a pause in fixing links, and upgraded the feeds:

```
ipkg update
ipkg install shellinabox
```

But note I haven't tested it
